const facts = [
    { fact: 'The world generated <span class="highlight">53.6 million</span> metric tons of e-waste in 2019.' },
    { fact: 'By 2030, global e-waste is expected to reach <span class="highlight">74 million</span> metric tons.' },
    { fact: 'Only <span class="highlight">17.4%</span> of global e-waste is properly recycled.' },
    { fact: '<span class="highlight">Asia</span> generates the highest amount of e-waste.' },
    { fact: 'E-waste is the <span class="highlight">fastest-growing</span> waste stream globally.' },
    { fact: 'More than <span class="highlight">50 million</span> tons of e-waste are discarded each year.' },
    { fact: 'The <span class="highlight">United States</span> generates approximately <span class="highlight">6.9 million</span> tons of e-waste annually.' },
    { fact: '<span class="highlight">Europe</span> has the highest e-waste recycling rate at around <span class="highlight">42%</span>.' },
    { fact: 'The average person generates about <span class="highlight">7 kg</span> of e-waste per year.' },
    { fact: 'Less than <span class="highlight">20%</span> of global e-waste is formally recycled.' },
    { fact: 'E-waste accounts for <span class="highlight">70%</span> of toxic waste found in landfills.' },
    { fact: 'E-waste contains harmful substances like <span class="highlight">lead, mercury, cadmium</span>, and <span class="highlight">arsenic</span>.' },
    { fact: 'Improper disposal of e-waste can contaminate <span class="highlight">soil and groundwater</span>.' },
    { fact: 'Burning e-waste releases toxic fumes that pollute the air.' },
    { fact: 'Lead exposure from e-waste can cause <span class="highlight">brain damage</span> in children.' },
    { fact: 'A single <span class="highlight">CRT monitor</span> contains up to <span class="highlight">4 kg</span> of lead.' },
    { fact: 'Mercury from e-waste can enter <span class="highlight">water bodies</span> and damage marine ecosystems.' },
    { fact: 'E-waste landfills produce <span class="highlight">methane</span>, a potent greenhouse gas.' },
    { fact: 'Recycling <span class="highlight">1 million</span> laptops saves energy equivalent to powering <span class="highlight">3,500</span> homes annually.' },
    { fact: 'E-waste contains valuable materials worth <span class="highlight">$57 billion</span> annually.' },
    { fact: 'Recycling e-waste can recover materials like <span class="highlight">gold, silver, platinum</span>, and <span class="highlight">palladium</span>.' },
    { fact: 'One metric ton of e-waste contains more gold than <span class="highlight">17 tons</span> of mined ore.' },
    { fact: 'Recovering metals from e-waste is <span class="highlight">13 times cheaper</span> than mining.' },
    { fact: 'Recycling <span class="highlight">1 million</span> cell phones can recover <span class="highlight">35 kg</span> of gold.' },
    { fact: 'The global e-waste recycling market is projected to reach <span class="highlight">$144 billion</span> by 2028.' },
    { fact: 'The informal e-waste sector employs over <span class="highlight">15 million</span> people worldwide.' },
    { fact: 'Proper recycling creates new <span class="highlight">job opportunities</span> in green industries.' },
    { fact: 'Over <span class="highlight">1.5 billion</span> smartphones are manufactured annually.' },
    { fact: 'The average smartphone user changes their phone every <span class="highlight">2-3 years</span>.' },
    { fact: 'Less than <span class="highlight">25%</span> of old electronics are returned for recycling.' },
    { fact: 'Around <span class="highlight">40%</span> of e-waste is illegally traded or dumped.' },
    { fact: 'Extended producer responsibility (<span class="highlight">EPR</span>) laws encourage manufacturers to handle e-waste.' },
    { fact: 'The circular economy promotes <span class="highlight">reuse, repair</span>, and recycling of electronics.' },
    { fact: 'Consumers can reduce e-waste by buying <span class="highlight">refurbished</span> electronics.' },
    { fact: 'Trade-in programs help reduce e-waste generation.' },
    { fact: 'The demand for <span class="highlight">sustainable electronics</span> is increasing.' },
    { fact: 'AI-powered e-waste sorting can improve <span class="highlight">recycling efficiency</span>.' },
    { fact: 'Modular designs make electronic devices easier to <span class="highlight">repair and upgrade</span>.' },
    { fact: 'Digital passports for electronics help track products for recycling.' },
    { fact: 'Eco-friendly batteries are being developed to replace <span class="highlight">lithium-ion batteries</span>.' },
    { fact: 'Blockchain technology is used to track e-waste recycling processes.' },
    { fact: '<span class="highlight">Smart bins</span> with IoT sensors can optimize e-waste collection.' },
    { fact: '<span class="highlight">Biodegradable circuit boards</span> are being researched for sustainable electronics.' },
    { fact: 'Governments are implementing strict <span class="highlight">e-waste laws</span> and policies.' },
    { fact: 'Community-led recycling drives raise awareness and increase e-waste collection.' }
];
module.exports = { data: facts };